In [1]:
# Import libraries

In [2]:
import numpy as np

In [3]:
myList = [1,2,3,3,1]

In [4]:
arr = np.array(myList)

In [5]:
arr

array([1, 2, 3, 3, 1])

In [6]:
arr.dtype

dtype('int32')

In [7]:
# make the array int 16 dudring the conversion

In [8]:
arr1 = np.array(myList, dtype='int16')

In [9]:
arr1

array([1, 2, 3, 3, 1], dtype=int16)

In [10]:
arr1.dtype

dtype('int16')

In [11]:
# change the data type 

In [12]:
f_arr = arr1.astype(np.float16)

In [13]:
f_arr

array([1., 2., 3., 3., 1.], dtype=float16)